---
#Ansible Playbook to Install Docker, download the appropriate images (Application & MySQL) 
#and start the containers with any configurations needed
 
- name: DevOps Group Project Playbook
  hosts: 40.112.93.237
  become: true
  gather_facts: no
  # vars:
  # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install pip3
      package:
        name: python3-pip
        state: present
    - name: Install docker
      package:
        name: docker.io
        state: present 
    - name: Install docker sdk
      pip:
        name: docker
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Run Docker container using the MySQL docker image
      command: docker run -d -p 3306:3306 -- name mysql_server mysql
    - name: Run Docker container using our application docker image
      command: docker run -d -p 8080:80 -- name application_container nlardas/devopsgroupproject               
    # - name: Run Docker container using the MySQL docker image
    #   docker_container:
    #     name: mysql_server
    #     image: mysql:latest
    #     state: started
    #     recreate: yes
    #     detach: true
    #     pull: yes
    #     ports:
    #       - 3306:3306
    #     env:
    #       MYSQL_ROOT_PASSWORD: AthTechDevOps
    # - name: Run Docker container using our application docker image
    #   docker_container:
    #     name: application_container
    #     image: nlardas/devopsgroupproject:latest
    #     state: started
    #     recreate: yes
    #     detach: true
    #     pull: yes
    #     ports:
    #       - 8080:8080