---
#Ansible Playbook to Install pip, Docker, Python docker sdk, start the docker service, create the docker network,
#configure and start our Docker containers with any configurations needed, providing a 10 second timeout in between to make sure the first container is fully operational
 
- name: DevOps Group Project Playbook
  hosts: 20.107.210.132
  become: true
  gather_facts: no

  tasks:
    - name: Install pip
      package:
        name: python-pip
        state: present
    - name: Install docker
      package:
        name: docker.io
        state: present 
    - name: Install docker sdk
      pip:
        name: docker
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started  
    - name: Create the network
      docker_network:
        name: devopsnetwork   
    - name: Create Docker container using the MySQL docker image
      docker_container:
        name: mysql_server
        image: mysql:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: AthTechDevOps
        networks:
          - name: devopsnetwork
    # - name: Sleep for 10 seconds to allow MySQL to start
    #   wait_for:
    #     timeout: 10
    - name: Wait for MySQL
      command: >
        docker exec {{ mysql_server|quote }}
        mysqladmin ping -u{{ DevOpsApplicationVM|quote }} -p{{ GroupProject21ApplicationVm|quote }}
      register: result
      until: not result.rc
      retries: 10
      delay: 10
    - name: Create Docker container using our application docker image
      docker_container:
        name: application_container
        image: nlardas/devopsgroupproject:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - 8080:8080
        networks:
          - name: devopsnetwork 