---
#Ansible Playbook to Install Docker, download the appropriate images (Application & MySQL) 
#and start the containers with any configurations needed
 
- name: DevOps Group Project Playbook
  hosts: 40.112.93.237
  become: true
  gather_facts: no

  tasks:
   - name: Run Docker container using the MySQL docker image
     docker_container:
       name: mysql_server
       image: mysql/mysql-server:latest
       state: started
       recreate: yes
       detach: true
       pull: yes
       ports:
        - "3306:3306"
       env:
        MYSQL_USER: root
        MYSQL_PASSWORD: AthTechDevOps
   - name: Run Docker container using our application docker image
     docker_container:
       name: application-container
       image: nlardas/devopsgroupproject:latest
       state: started
       recreate: yes
       detach: true
       pull: yes
       ports:
        - "8080:8080"
  #
  #  - name: Install Docker
  #    apt:
  #     name: "docker-ce"
  #     state: present
  #     force_apt_get: "yes"
  #   vars:
  # ansible_python_interpreter: /usr/bin/python3