---
#Ansible Playbook to Install Docker, download the appropriate images (Application & MySQL) 
#and start the containers with any configurations needed
 
- name: DevOps Group Project Playbook
  hosts: 40.112.93.237
  become: true
  gather_facts: no

  tasks:
   - name: install packages
     package:
       name: nginx
       state: latest
  # tasks:
  #   - name: Run Docker container using our application docker image
  #     docker_container:
  #       name: application-container
  #       image: nlardas/devopsgroupproject:latest
  #       state: started
  #       recreate: yes
  #       detach: true
  #       pull: yes
  #       ports:
  #         - "8080:8080"