---
#Ansible Playbook to Install Docker, download the appropriate images (Application & MySQL) 
#and start the containers with any configurations needed
 
- name: DevOps Group Project Playbook
  hosts: 20.107.210.132
  become: true
  gather_facts: no

  tasks:
    - name: Install pip
      package:
        name: python-pip
        state: present
    - name: Install docker
      package:
        name: docker.io
        state: present 
    - name: Install docker sdk
      pip:
        name: docker
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started  
    - name: Create the network
      docker_network:
        name: devopsnetwork   
    - name: Run Docker container using the MySQL docker image
      docker_container:
        name: mysql_server
        image: mysql:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: AthTechDevOps
        networks:
          - name: devopsnetwork
    - name: Create Docker container using our application docker image
      docker_container:
        name: application_container
        image: nlardas/devopsgroupproject:latest
        state: present
        recreate: yes
        detach: true
        pull: yes
        ports:
          - 8080:8080
        networks:
          - name: devopsnetwork
    - name: Start the Application
      command: docker start application_container